version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: mydatabase
    networks:
      - message-broker-network

volumes:
  mongo-data:

networks:
  message-broker-network:
    external: true
