version: '3.8'

services:
  data-generator:
    build: .
    container_name: data-generator
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - message-broker-network

networks:
  message-broker-network:
    external: true
