version: '3.8'

services:
  nodejs-service:
    build: ./nodejs-service
    container_name: nodejs-service
    ports:
      - "5000:5000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_URI=mongodb://mongo:27017

  rails-service:
    build: ./rails-service
    container_name: rails-service
    ports:
      - "5001:5001"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
