version: '3.8'

services:
  nodejs-service:
    build: ./nodejs-service
    container_name: nodejs-service
    ports:
      - "5000:5000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - message-broker-network

  rails-service:
    build: ./rails-service
    container_name: rails-service
    ports:
      - "5001:5001"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - message-broker-network
  
  springboot-service:
    build: ./springboot-service
    container_name: springboot-service
    ports:
      - "5002:5002"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - message-broker-network
  
  phoenix-service:
    build: ./phoenix_service
    container_name: phoenix-service
    ports:
      - "5003:4000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
      - SECRET_KEY_BASE=MjBaxfQbMRMPMdG2Gxv/3EhIJmjJlTH+HbOQbmPxk12W2RjFkW8TlgKdgD5OO768
    networks:
      - message-broker-network

networks:
  message-broker-network:
    external: true
